### ISSUE TITLE
Support for BGW210-700?

### ISSUE THREAD

**Issue by gcordell** [metekamil/ATT-Uverse-Automated-Router-Rebooter#1]
Any chance you'd be willing to add support for the BGW210-770?  I suck at node and can't figure it out, but would love to tie this into another script that I'm writing to automatically reboot when my router loses it's internet connection (which happens **every** day...

Landing Page:  /cgi-bin/home.ha
Page with Security Code:  /cgi-bin/restart.ha
Page after Security Code: cgi-bin/restart.ha

Let me know anything else that would help (happy to do a screen share if need be!)

**Comment by metekamil** [comment]
Please share those web pages HTML source (via browsers view source option) using Gist or a similar service and I'll see if this script will work for that.  Also screen shots if possible.
