### ISSUE TITLE
This script shuts down router, does not reboot

### ISSUE THREAD

**Issue by terrisgit** [metekamil/ATT-Uverse-Automated-Router-Rebooter#3]
I have a battery backup supplied by AT&T. This script turns off the router.

If you have this problem, use this repo instead: https://github.com/terrisgit/ATT-Uverse-Router-Reconnect/

**Comment by terrisgit** [comment]
I tried this:

```    var form = {
        "RESET_BB" : 'Restart',
        "THISPAGE" : 'A_0_0',
        "NEXTPAGE" : 'A_0_0_POST',
        "NONCE": nonce,
        "CMSKICK": ""
    };
```

**Comment by metekamil** [comment]
Thanks @terrisgit. I've pulled in your changes. Worked for my router also which doesn't use battery backup.
